# Generated by Django 3.0.8 on 2021-04-14 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='conact_subject',
            new_name='contact_subject',
        ),
    ]
