# Generated by Django 3.0.8 on 2021-06-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filez', '0002_filesdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='filezdata',
            name='month',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
