# Generated by Django 3.0.8 on 2021-04-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='User_Images/default.gif', null=True, upload_to='User_Images/'),
        ),
    ]
